# Copyright 2026 Tensor Auto Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from opentau.scripts.grpc import robot_inference_pb2 as robot__inference__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in robot_inference_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RobotPolicyServiceStub:
    """Service for robot policy inference"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActionChunk = channel.unary_unary(
            "/robot_inference.RobotPolicyService/GetActionChunk",
            request_serializer=robot__inference__pb2.ObservationRequest.SerializeToString,
            response_deserializer=robot__inference__pb2.ActionChunkResponse.FromString,
            _registered_method=True,
        )
        self.StreamActionChunks = channel.stream_stream(
            "/robot_inference.RobotPolicyService/StreamActionChunks",
            request_serializer=robot__inference__pb2.ObservationRequest.SerializeToString,
            response_deserializer=robot__inference__pb2.ActionChunkResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/robot_inference.RobotPolicyService/HealthCheck",
            request_serializer=robot__inference__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=robot__inference__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class RobotPolicyServiceServicer:
    """Service for robot policy inference"""

    def GetActionChunk(self, request, context):
        """Get action chunk from observations (single request-response)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamActionChunks(self, request_iterator, context):
        """Streaming version for continuous inference (robot sends observations, server sends action chunks)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RobotPolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetActionChunk": grpc.unary_unary_rpc_method_handler(
            servicer.GetActionChunk,
            request_deserializer=robot__inference__pb2.ObservationRequest.FromString,
            response_serializer=robot__inference__pb2.ActionChunkResponse.SerializeToString,
        ),
        "StreamActionChunks": grpc.stream_stream_rpc_method_handler(
            servicer.StreamActionChunks,
            request_deserializer=robot__inference__pb2.ObservationRequest.FromString,
            response_serializer=robot__inference__pb2.ActionChunkResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=robot__inference__pb2.HealthCheckRequest.FromString,
            response_serializer=robot__inference__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "robot_inference.RobotPolicyService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("robot_inference.RobotPolicyService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RobotPolicyService:
    """Service for robot policy inference"""

    @staticmethod
    def GetActionChunk(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/robot_inference.RobotPolicyService/GetActionChunk",
            robot__inference__pb2.ObservationRequest.SerializeToString,
            robot__inference__pb2.ActionChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamActionChunks(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/robot_inference.RobotPolicyService/StreamActionChunks",
            robot__inference__pb2.ObservationRequest.SerializeToString,
            robot__inference__pb2.ActionChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/robot_inference.RobotPolicyService/HealthCheck",
            robot__inference__pb2.HealthCheckRequest.SerializeToString,
            robot__inference__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
